# Notepad++
# Notepad++ is a text and source code editor for use with Microsoft Windows. 
---
- hosts: all
  tasks:
  - name: Install Notepad
    win_chocolatey:
       name: notepadplusplus
       state: present
    tags:
      - install

  - name: Uninstall Notepad
    win_chocolatey:
       name: notepadplusplus
       state: absent
    tags:
      - uninstall
