# Notepad ++
# Замечательный текстовый редактор имеющий миллион функций и распространяющийся <strong>АБСОЛЮТНО БЕСПЛАТНО</strong>
---
- hosts: all
  tasks:
  - name: Install Notepad
    win_chocolatey:
       name: notepadplusplus
       state: present
    tags:
      - install

  - name: Uninstall Notepad
    win_chocolatey:
       name: notepadplusplus
       state: absent
    tags:
      - uninstall
